### ISSUE TITLE
TB_get_bk and TB_get_ei behaviour

### ISSUE THREAD

**Issue by DMFTSever** [QcmPlab/DMFTtools#1]
Hey everyone,
I noticed that currently the the behaviour of TB_get_bk and TB_get_ei in TB_BASIS.f90 is to call TB_reciprocal_basis without checking if bk or ei where already set by the user. In my eyes, this is a quit unintuitive behaviour. Also it can potentially result in bugs when only one of the values was set by the user and then for what reason ever the user makes a call to TB_get_xx (where xx is the basis the user already set). This then would return the reciprocal of the default basis and not the user set basis. I think the least intrusive way to fix this would be to  place a warning. Of course this does not prevent the user to introduce a bug in his/her code. For that I would either raise an error and leave the current behaviour or: check wether the basis was already set. If so return it. If not check whether the other basis was set. If so calculate new basis. If not through an error. 
Best, Sever

**Comment by aamaricci** [comment]
I see the point. Shame on me, I actually did not realize that inside TB_get_ei/bk there is a call to TB_reciprocal_basis.
That is very very dangerous. 
I guess originally this should have been thought of as:
IF the required basis, resp. ei/bk, is not available THEN obtain it.
Yet the way it is written is bugged and actually led to the TB_build_kgrid bug solved in the last commit. 

I would implement the following modifications:
IF (required basis not set) obtain it with a warning. 

Plus I would take care of getting and setting reciprocal basis every time a specific basis is set, i.e. get ei if set_bk is called, get bk if set_ei is called. 

thanks a lot for pointing this out.
